apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\super magic\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alertmanager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\super magic\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -c
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: alertmanager
    spec:
      containers:
        - args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
          image: prom/alertmanager:latest
          name: alertmanager
          ports:
            - containerPort: 9093
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/alertmanager/alertmanager.yml
              name: alertmanager-cm0
              subPath: alertmanager.yml
            - mountPath: /alertmanager
              name: alertmanager-data
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: alertmanager.yml
                path: alertmanager.yml
            name: alertmanager-cm0
          name: alertmanager-cm0
        - name: alertmanager-data
          persistentVolumeClaim:
            claimName: alertmanager-data
